#!/usr/bin/perl -w

# perl script to generate postscript. 
# Because I'm not doing trig in ps, nor am 
# I about to use ps to write a web cgi program.. 

# this needs cgiified later

{
    local $/;
    $help=<DATA>;
}

print STDOUT "hi\n";

#open file and print header info 
$fn='outfile.ps'; # fixme
open ($outfile, "|>") || die "can't open outfile";
print $outfile 
"%!
%% pattern for bellows generated by bellofy.pl

/mm {360 mul 127 div} def % cause I don't do points
";

LOOP:
while(){
    print "Select an action. Enter...
    B to create a bellows pattern
    Q to quit:\n";
    $choice=uc(<STDIN>);
    chomp $choice;
    if ($choice eq "B"){
        &get_UI;
    } elsif ($choice eq "Q") {
        exit;
    } else {
        next LOOP;
    }
} #end first UI loop 

sub get_UI{
   print "enter your rear standard inner bellows width in mm ";
    $riw=<STDIN> ; chomp $riw; $riw=~s/\s//g;
    if($riw=~/[^0-9]/){print "Illegal characters in input text.\n"; return}

    print "enter your rear standard outer bellows width in mm ";
    $row=<STDIN>; chomp $row; $row=~s/\s//g;
    if($row=~/[^0-9]/){print "Illegal characters in input text.\n"; return}

    print "enter your front standard inner bellows width in mm ";
    $fiw=<STDIN>; chomp $fiw; $fiw=~s/\s//g;
    if($fiw=~/[^0-9]/){print "Illegal characters in input text.\n"; return}

    print "enter your front standard outer bellows width in mm ";
    $fow=<STDIN>; chomp $fow; $fow=~s/\s//g;
    if($fow=~/[^0-9]/){print "Illegal characters in input text.\n"; return}

    # bounds checking here 

    print "generating pattern with parameters row=$row, riw=$riw, fow=$fow, fiw=$fiw...\n";

    &bellofy;

    return;
}# bellofy UI loop 2

sub bellofy{    # bellows-drawing algorithm.
    print $outfile "
    newpath
    0 0 moveto
    0 $row lineto
    $row $row lineto
    $row 0 lineto
    0 0 lineto

    0 0 moveto
    0 $riw lineto
    $riw $riw lineto
    $riw 0 lineto
    0 0 lineto

    0 0 moveto
    0 $fiw lineto
    $fiw $fiw lineto
    $fiw 0 lineto
    0 0 lineto

    0 0 moveto
    0 $fow lineto
    $fow $fow lineto
    $fow 0 lineto
    0 0 lineto

    2 setlinewidth
    stroke
    showpage 
    ";




    # precalculation of globally-relevant parameters
    # length of top outer corner lines from bellows length and vector math
    # length of side outer corner lines from bellows length and vector math
    # distance between pleats ?

    # coordinate transform subroutine? translation+rotation??
    # save lines as objects and find intersections with subroutine? 
    # draw_line subroutine? 

    # draw top trapezoid. Center line for convenience. Necessary because these 
    # lines are extra? Maybe just define.

    # draw top, shorter outer pleat lines. Can we calc distance and just linearly scale 
    # the distance between them?  

    # Can we calculate the location and distance of the longer outer-pleat lines, also linearly
    # scale, and draw them longer? Calculate how much longer than inner pleates from trig?

    # we should draw the zig-zag on the left side using the endpoints of the pleat lines.
    # then the zigzags are taken care of. 
    
    # Coordinate transform to the side trapezoid, and draw the side pleat lines same way? 
    # Should magically touch?

    # coordinate transform and do both of the above once to save computation? meh. bottom 
    # needs drawn twice. Be a pal and draw slopey lines. Maybe on all panels?

}
#
__END__
    print "\n\n";
    return;

}#bellowfi

__DATA__

Instructions?


